import type {NextPage} from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Maze from "../components/Maze/Maze";
import Toolbar from "../components/Toolbar/Toolbar";
import {useEffect, useState} from "react";

const Home: NextPage = () => {
    const [currentTool, setCurrentTool] = useState("wall");
    const updateTool = (toolType: string) => {
        setCurrentTool(toolType);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header style={{display: "flex", justifyContent: "center", marginTop: "2rem"}}>
                <Toolbar selectTool={updateTool} />
            </header>

            <main
                draggable={"false"}
                style={{display: "flex", justifyContent: "center", marginTop: "2rem"}}>
                <Maze actionType={"add"} nodeType={currentTool} />
            </main>
        </div>
    );
};

export default Home;
